#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym__sep_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_LT_DASH = 4,
  sym_drop = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  sym_number = 10,
  anon_sym_PLUS = 11,
  anon_sym_DASH = 12,
  anon_sym_STAR = 13,
  anon_sym_SLASH = 14,
  anon_sym_DASH_DASH = 15,
  aux_sym_comment_token1 = 16,
  sym_program = 17,
  sym__sep = 18,
  sym__statement = 19,
  sym_definition = 20,
  sym__expression = 21,
  sym_apply = 22,
  sym__atom = 23,
  sym_fn = 24,
  sym_param = 25,
  sym_block = 26,
  sym_primitive = 27,
  sym_comment = 28,
  aux_sym_program_repeat1 = 29,
  aux_sym_apply_repeat1 = 30,
  aux_sym_fn_repeat1 = 31,
  aux_sym_block_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym__sep_token1] = "_sep_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_LT_DASH] = "<-",
  [sym_drop] = "drop",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_number] = "number",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH_DASH] = "--",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_program] = "program",
  [sym__sep] = "_sep",
  [sym__statement] = "_statement",
  [sym_definition] = "definition",
  [sym__expression] = "_expression",
  [sym_apply] = "apply",
  [sym__atom] = "_atom",
  [sym_fn] = "fn",
  [sym_param] = "param",
  [sym_block] = "block",
  [sym_primitive] = "primitive",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_apply_repeat1] = "apply_repeat1",
  [aux_sym_fn_repeat1] = "fn_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym__sep_token1] = aux_sym__sep_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [sym_drop] = sym_drop,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_number] = sym_number,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_program] = sym_program,
  [sym__sep] = sym__sep,
  [sym__statement] = sym__statement,
  [sym_definition] = sym_definition,
  [sym__expression] = sym__expression,
  [sym_apply] = sym_apply,
  [sym__atom] = sym__atom,
  [sym_fn] = sym_fn,
  [sym_param] = sym_param,
  [sym_block] = sym_block,
  [sym_primitive] = sym_primitive,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_apply_repeat1] = aux_sym_apply_repeat1,
  [aux_sym_fn_repeat1] = aux_sym_fn_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__sep_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_drop] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__sep] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_apply] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_apply_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fn_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_params = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_params] = "params",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_name, 0},
  [2] =
    {field_body, 3},
    {field_params, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '\n', 4,
        '(', 8,
        ')', 9,
        '*', 17,
        '+', 15,
        '-', 16,
        '.', 7,
        '/', 18,
        ';', 5,
        '<', 1,
        '{', 10,
        '}', 11,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym__sep_token1);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_drop);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(19);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 21},
  [41] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym__sep_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [sym_drop] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(39),
    [sym__statement] = STATE(27),
    [sym_definition] = STATE(33),
    [sym__expression] = STATE(33),
    [sym_apply] = STATE(25),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(25),
    [sym_primitive] = STATE(18),
    [sym_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_drop] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [2] = {
    [sym__sep] = STATE(13),
    [sym__expression] = STATE(30),
    [sym_apply] = STATE(25),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(25),
    [sym_primitive] = STATE(18),
    [sym_comment] = STATE(2),
    [aux_sym_block_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(13),
    [aux_sym__sep_token1] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(19),
    [sym_drop] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_number] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [3] = {
    [sym__sep] = STATE(13),
    [sym__expression] = STATE(36),
    [sym_apply] = STATE(25),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(25),
    [sym_primitive] = STATE(18),
    [sym_comment] = STATE(3),
    [aux_sym_block_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(23),
    [aux_sym__sep_token1] = ACTIONS(26),
    [anon_sym_SEMI] = ACTIONS(26),
    [sym_drop] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(32),
    [anon_sym_RBRACE] = ACTIONS(35),
    [sym_number] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(37),
    [anon_sym_DASH] = ACTIONS(40),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(37),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [4] = {
    [sym__sep] = STATE(13),
    [sym__expression] = STATE(28),
    [sym_apply] = STATE(25),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(25),
    [sym_primitive] = STATE(18),
    [sym_comment] = STATE(4),
    [aux_sym_block_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(13),
    [aux_sym__sep_token1] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(19),
    [sym_drop] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(43),
    [sym_number] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [5] = {
    [sym__statement] = STATE(22),
    [sym_definition] = STATE(33),
    [sym__expression] = STATE(33),
    [sym_apply] = STATE(25),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(25),
    [sym_primitive] = STATE(18),
    [sym_comment] = STATE(5),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_identifier] = ACTIONS(7),
    [sym_drop] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [6] = {
    [sym__statement] = STATE(35),
    [sym_definition] = STATE(33),
    [sym__expression] = STATE(33),
    [sym_apply] = STATE(25),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(25),
    [sym_primitive] = STATE(18),
    [sym_comment] = STATE(6),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_identifier] = ACTIONS(49),
    [sym_drop] = ACTIONS(52),
    [anon_sym_LPAREN] = ACTIONS(55),
    [sym_number] = ACTIONS(58),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(64),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [7] = {
    [sym__expression] = STATE(20),
    [sym_apply] = STATE(25),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(25),
    [sym_block] = STATE(20),
    [sym_primitive] = STATE(18),
    [sym_comment] = STATE(7),
    [sym_identifier] = ACTIONS(13),
    [sym_drop] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(69),
    [sym_number] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(17),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(17), 1,
      anon_sym_DASH,
    STATE(8), 1,
      sym_comment,
    STATE(11), 1,
      aux_sym_apply_repeat1,
    STATE(17), 1,
      sym__atom,
    STATE(18), 1,
      sym_primitive,
    ACTIONS(13), 2,
      sym_number,
      sym_identifier,
    ACTIONS(15), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(71), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [34] = 9,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(17), 1,
      anon_sym_DASH,
    STATE(8), 1,
      aux_sym_apply_repeat1,
    STATE(9), 1,
      sym_comment,
    STATE(17), 1,
      sym__atom,
    STATE(18), 1,
      sym_primitive,
    ACTIONS(13), 2,
      sym_number,
      sym_identifier,
    ACTIONS(15), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [68] = 11,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      sym_drop,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      anon_sym_DASH,
    STATE(9), 1,
      sym__atom,
    STATE(10), 1,
      sym_comment,
    STATE(18), 1,
      sym_primitive,
    STATE(32), 1,
      sym__expression,
    ACTIONS(13), 2,
      sym_number,
      sym_identifier,
    STATE(25), 2,
      sym_apply,
      sym_fn,
    ACTIONS(15), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [106] = 8,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(83), 1,
      anon_sym_DASH,
    STATE(17), 1,
      sym__atom,
    STATE(18), 1,
      sym_primitive,
    ACTIONS(77), 2,
      sym_number,
      sym_identifier,
    STATE(11), 2,
      sym_comment,
      aux_sym_apply_repeat1,
    ACTIONS(80), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [138] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(88), 1,
      anon_sym_DASH,
    STATE(12), 1,
      sym_comment,
    ACTIONS(86), 11,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [161] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(92), 1,
      anon_sym_DASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(90), 10,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [183] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(94), 1,
      anon_sym_DASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(35), 10,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [205] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(98), 1,
      anon_sym_DASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(96), 9,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [226] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(102), 1,
      anon_sym_LT_DASH,
    ACTIONS(104), 1,
      anon_sym_DASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(100), 8,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [249] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(108), 1,
      anon_sym_DASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(106), 9,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [270] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(104), 1,
      anon_sym_DASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(100), 9,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [291] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(110), 1,
      anon_sym_DASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(47), 8,
      ts_builtin_sym_end,
      sym_drop,
      anon_sym_LPAREN,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [311] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [324] = 6,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      sym_comment,
    STATE(23), 1,
      aux_sym_fn_repeat1,
    STATE(37), 1,
      sym_param,
  [343] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym__sep,
    STATE(22), 1,
      sym_comment,
    ACTIONS(19), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [360] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(120), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      sym_param,
    STATE(23), 2,
      sym_comment,
      aux_sym_fn_repeat1,
  [377] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [390] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [403] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [416] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    STATE(19), 1,
      sym__sep,
    STATE(27), 1,
      sym_comment,
    ACTIONS(19), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [433] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      sym__sep,
    STATE(28), 1,
      sym_comment,
    ACTIONS(19), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [450] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(127), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [463] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      sym__sep,
    STATE(30), 1,
      sym_comment,
    ACTIONS(19), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [480] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(131), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [493] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [505] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(135), 3,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [517] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(21), 1,
      aux_sym_fn_repeat1,
    STATE(34), 1,
      sym_comment,
    STATE(37), 1,
      sym_param,
  [533] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(19), 1,
      sym__sep,
    STATE(35), 1,
      sym_comment,
    ACTIONS(19), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [547] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(14), 1,
      sym__sep,
    STATE(36), 1,
      sym_comment,
    ACTIONS(19), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [561] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [572] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(38), 1,
      sym_comment,
    ACTIONS(139), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [583] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_comment,
  [593] = 3,
    ACTIONS(143), 1,
      anon_sym_DASH_DASH,
    ACTIONS(145), 1,
      aux_sym_comment_token1,
    STATE(40), 1,
      sym_comment,
  [603] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 34,
  [SMALL_STATE(10)] = 68,
  [SMALL_STATE(11)] = 106,
  [SMALL_STATE(12)] = 138,
  [SMALL_STATE(13)] = 161,
  [SMALL_STATE(14)] = 183,
  [SMALL_STATE(15)] = 205,
  [SMALL_STATE(16)] = 226,
  [SMALL_STATE(17)] = 249,
  [SMALL_STATE(18)] = 270,
  [SMALL_STATE(19)] = 291,
  [SMALL_STATE(20)] = 311,
  [SMALL_STATE(21)] = 324,
  [SMALL_STATE(22)] = 343,
  [SMALL_STATE(23)] = 360,
  [SMALL_STATE(24)] = 377,
  [SMALL_STATE(25)] = 390,
  [SMALL_STATE(26)] = 403,
  [SMALL_STATE(27)] = 416,
  [SMALL_STATE(28)] = 433,
  [SMALL_STATE(29)] = 450,
  [SMALL_STATE(30)] = 463,
  [SMALL_STATE(31)] = 480,
  [SMALL_STATE(32)] = 493,
  [SMALL_STATE(33)] = 505,
  [SMALL_STATE(34)] = 517,
  [SMALL_STATE(35)] = 533,
  [SMALL_STATE(36)] = 547,
  [SMALL_STATE(37)] = 561,
  [SMALL_STATE(38)] = 572,
  [SMALL_STATE(39)] = 583,
  [SMALL_STATE(40)] = 593,
  [SMALL_STATE(41)] = 603,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sep, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sep, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, 0, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rho(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
