#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 52
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym__sep_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_LT_DASH = 4,
  sym_drop = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_string_token1 = 13,
  sym_escape_sequence = 14,
  sym_number = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  anon_sym_DASH_DASH = 20,
  aux_sym_comment_token1 = 21,
  sym_program = 22,
  sym__sep = 23,
  sym__statement = 24,
  sym_definition = 25,
  sym__expression = 26,
  sym_apply = 27,
  sym__atom = 28,
  sym_fn = 29,
  sym_param = 30,
  sym_block = 31,
  sym_array = 32,
  sym_string = 33,
  sym_primitive = 34,
  sym_comment = 35,
  aux_sym_program_repeat1 = 36,
  aux_sym_apply_repeat1 = 37,
  aux_sym_fn_repeat1 = 38,
  aux_sym_block_repeat1 = 39,
  aux_sym_string_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym__sep_token1] = "_sep_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_LT_DASH] = "<-",
  [sym_drop] = "drop",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH_DASH] = "--",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_program] = "program",
  [sym__sep] = "_sep",
  [sym__statement] = "_statement",
  [sym_definition] = "definition",
  [sym__expression] = "_expression",
  [sym_apply] = "apply",
  [sym__atom] = "_atom",
  [sym_fn] = "fn",
  [sym_param] = "param",
  [sym_block] = "block",
  [sym_array] = "array",
  [sym_string] = "string",
  [sym_primitive] = "primitive",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_apply_repeat1] = "apply_repeat1",
  [aux_sym_fn_repeat1] = "fn_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym__sep_token1] = aux_sym__sep_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [sym_drop] = sym_drop,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_program] = sym_program,
  [sym__sep] = sym__sep,
  [sym__statement] = sym__statement,
  [sym_definition] = sym_definition,
  [sym__expression] = sym__expression,
  [sym_apply] = sym_apply,
  [sym__atom] = sym__atom,
  [sym_fn] = sym_fn,
  [sym_param] = sym_param,
  [sym_block] = sym_block,
  [sym_array] = sym_array,
  [sym_string] = sym_string,
  [sym_primitive] = sym_primitive,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_apply_repeat1] = aux_sym_apply_repeat1,
  [aux_sym_fn_repeat1] = aux_sym_fn_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__sep_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_drop] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__sep] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_apply] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_apply_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fn_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_params = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_params] = "params",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_name, 0},
  [2] =
    {field_body, 3},
    {field_params, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '\n', 6,
        '"', 16,
        '(', 10,
        ')', 11,
        '*', 26,
        '+', 24,
        '-', 25,
        '.', 9,
        '/', 27,
        ';', 7,
        '<', 2,
        '[', 14,
        '\\', 3,
        ']', 15,
        '{', 12,
        '}', 13,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(16);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(20);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym__sep_token1);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_drop);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(19);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 31},
  [50] = {.lex_state = 0},
  [51] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym__sep_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [sym_drop] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(50),
    [sym__statement] = STATE(35),
    [sym_definition] = STATE(44),
    [sym__expression] = STATE(44),
    [sym_apply] = STATE(27),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(27),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym_primitive] = STATE(16),
    [sym_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_drop] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [2] = {
    [sym__sep] = STATE(21),
    [sym__expression] = STATE(45),
    [sym_apply] = STATE(27),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(27),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym_primitive] = STATE(16),
    [sym_comment] = STATE(2),
    [aux_sym_block_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(23),
    [aux_sym__sep_token1] = ACTIONS(26),
    [anon_sym_SEMI] = ACTIONS(26),
    [sym_drop] = ACTIONS(29),
    [anon_sym_LPAREN] = ACTIONS(32),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(40),
    [sym_number] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_DASH] = ACTIONS(46),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [3] = {
    [sym__sep] = STATE(21),
    [sym__expression] = STATE(37),
    [sym_apply] = STATE(27),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(27),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym_primitive] = STATE(16),
    [sym_comment] = STATE(3),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(17),
    [aux_sym__sep_token1] = ACTIONS(49),
    [anon_sym_SEMI] = ACTIONS(49),
    [sym_drop] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [4] = {
    [sym__sep] = STATE(21),
    [sym__expression] = STATE(40),
    [sym_apply] = STATE(27),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(27),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym_primitive] = STATE(16),
    [sym_comment] = STATE(4),
    [aux_sym_block_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(17),
    [aux_sym__sep_token1] = ACTIONS(49),
    [anon_sym_SEMI] = ACTIONS(49),
    [sym_drop] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [5] = {
    [sym__statement] = STATE(29),
    [sym_definition] = STATE(44),
    [sym__expression] = STATE(44),
    [sym_apply] = STATE(27),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(27),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym_primitive] = STATE(16),
    [sym_comment] = STATE(5),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_identifier] = ACTIONS(7),
    [sym_drop] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [6] = {
    [sym__statement] = STATE(43),
    [sym_definition] = STATE(44),
    [sym__expression] = STATE(44),
    [sym_apply] = STATE(27),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(27),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym_primitive] = STATE(16),
    [sym_comment] = STATE(6),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(59),
    [sym_drop] = ACTIONS(62),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(71),
    [sym_number] = ACTIONS(74),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(80),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(77),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [7] = {
    [sym__expression] = STATE(34),
    [sym_apply] = STATE(27),
    [sym__atom] = STATE(9),
    [sym_fn] = STATE(27),
    [sym_block] = STATE(34),
    [sym_array] = STATE(16),
    [sym_string] = STATE(16),
    [sym_primitive] = STATE(16),
    [sym_comment] = STATE(7),
    [sym_identifier] = ACTIONS(17),
    [sym_drop] = ACTIONS(83),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(92), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(101), 1,
      anon_sym_DASH,
    STATE(19), 1,
      sym__atom,
    ACTIONS(89), 2,
      sym_number,
      sym_identifier,
    STATE(8), 2,
      sym_comment,
      aux_sym_apply_repeat1,
    ACTIONS(98), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(16), 3,
      sym_array,
      sym_string,
      sym_primitive,
    ACTIONS(87), 5,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
  [41] = 11,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_DASH,
    STATE(9), 1,
      sym_comment,
    STATE(11), 1,
      aux_sym_apply_repeat1,
    STATE(19), 1,
      sym__atom,
    ACTIONS(17), 2,
      sym_number,
      sym_identifier,
    ACTIONS(19), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(16), 3,
      sym_array,
      sym_string,
      sym_primitive,
    ACTIONS(104), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [83] = 13,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      sym_drop,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_DASH,
    STATE(9), 1,
      sym__atom,
    STATE(10), 1,
      sym_comment,
    STATE(42), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_identifier,
    STATE(27), 2,
      sym_apply,
      sym_fn,
    ACTIONS(19), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(16), 3,
      sym_array,
      sym_string,
      sym_primitive,
  [129] = 11,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_DASH,
    STATE(8), 1,
      aux_sym_apply_repeat1,
    STATE(11), 1,
      sym_comment,
    STATE(19), 1,
      sym__atom,
    ACTIONS(17), 2,
      sym_number,
      sym_identifier,
    ACTIONS(19), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(16), 3,
      sym_array,
      sym_string,
      sym_primitive,
    ACTIONS(106), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [171] = 11,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(108), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_apply_repeat1,
    STATE(19), 1,
      sym__atom,
    ACTIONS(17), 2,
      sym_number,
      sym_identifier,
    ACTIONS(19), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(16), 3,
      sym_array,
      sym_string,
      sym_primitive,
  [210] = 11,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_DASH,
    ACTIONS(110), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      aux_sym_apply_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(19), 1,
      sym__atom,
    ACTIONS(17), 2,
      sym_number,
      sym_identifier,
    ACTIONS(19), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(16), 3,
      sym_array,
      sym_string,
      sym_primitive,
  [249] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(114), 1,
      anon_sym_DASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(112), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [274] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(118), 1,
      anon_sym_DASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(116), 12,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [298] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(122), 1,
      anon_sym_DASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(120), 12,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [322] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(126), 1,
      anon_sym_DASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(124), 12,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [346] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(130), 1,
      anon_sym_DASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(128), 12,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [370] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(134), 1,
      anon_sym_DASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(132), 12,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [394] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(138), 1,
      anon_sym_DASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(136), 12,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [418] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(142), 1,
      anon_sym_DASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(140), 12,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [442] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(146), 1,
      anon_sym_DASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(144), 12,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [466] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(148), 1,
      anon_sym_DASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(35), 12,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [490] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(122), 1,
      anon_sym_DASH,
    ACTIONS(150), 1,
      anon_sym_LT_DASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [515] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(152), 1,
      anon_sym_DASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(57), 10,
      ts_builtin_sym_end,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [537] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(154), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [550] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(104), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [563] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(156), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(47), 1,
      sym_param,
    STATE(28), 2,
      sym_comment,
      aux_sym_fn_repeat1,
  [580] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym__sep,
    STATE(29), 1,
      sym_comment,
    ACTIONS(49), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [597] = 6,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(163), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_fn_repeat1,
    STATE(30), 1,
      sym_comment,
    STATE(47), 1,
      sym_param,
  [616] = 4,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(172), 1,
      anon_sym_DASH_DASH,
    ACTIONS(169), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
    STATE(31), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [631] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [644] = 5,
    ACTIONS(172), 1,
      anon_sym_DASH_DASH,
    ACTIONS(176), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_comment,
    STATE(38), 1,
      aux_sym_string_repeat1,
    ACTIONS(178), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [661] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(174), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [674] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym__sep,
    STATE(35), 1,
      sym_comment,
    ACTIONS(49), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [691] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(180), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [704] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      sym__sep,
    STATE(37), 1,
      sym_comment,
    ACTIONS(49), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [721] = 5,
    ACTIONS(172), 1,
      anon_sym_DASH_DASH,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    STATE(31), 1,
      aux_sym_string_repeat1,
    STATE(38), 1,
      sym_comment,
    ACTIONS(178), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [738] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(39), 1,
      sym_comment,
    ACTIONS(184), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [751] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      sym__sep,
    STATE(40), 1,
      sym_comment,
    ACTIONS(49), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [768] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(163), 1,
      sym_identifier,
    STATE(30), 1,
      aux_sym_fn_repeat1,
    STATE(41), 1,
      sym_comment,
    STATE(47), 1,
      sym_param,
  [784] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(42), 1,
      sym_comment,
    ACTIONS(188), 3,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [796] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(25), 1,
      sym__sep,
    STATE(43), 1,
      sym_comment,
    ACTIONS(49), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [810] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(44), 1,
      sym_comment,
    ACTIONS(190), 3,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [822] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(23), 1,
      sym__sep,
    STATE(45), 1,
      sym_comment,
    ACTIONS(49), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [836] = 3,
    ACTIONS(172), 1,
      anon_sym_DASH_DASH,
    STATE(46), 1,
      sym_comment,
    ACTIONS(192), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      sym_escape_sequence,
  [848] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(47), 1,
      sym_comment,
    ACTIONS(194), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [859] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(196), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [870] = 3,
    ACTIONS(172), 1,
      anon_sym_DASH_DASH,
    ACTIONS(198), 1,
      aux_sym_comment_token1,
    STATE(49), 1,
      sym_comment,
  [880] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      sym_comment,
  [890] = 1,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 41,
  [SMALL_STATE(10)] = 83,
  [SMALL_STATE(11)] = 129,
  [SMALL_STATE(12)] = 171,
  [SMALL_STATE(13)] = 210,
  [SMALL_STATE(14)] = 249,
  [SMALL_STATE(15)] = 274,
  [SMALL_STATE(16)] = 298,
  [SMALL_STATE(17)] = 322,
  [SMALL_STATE(18)] = 346,
  [SMALL_STATE(19)] = 370,
  [SMALL_STATE(20)] = 394,
  [SMALL_STATE(21)] = 418,
  [SMALL_STATE(22)] = 442,
  [SMALL_STATE(23)] = 466,
  [SMALL_STATE(24)] = 490,
  [SMALL_STATE(25)] = 515,
  [SMALL_STATE(26)] = 537,
  [SMALL_STATE(27)] = 550,
  [SMALL_STATE(28)] = 563,
  [SMALL_STATE(29)] = 580,
  [SMALL_STATE(30)] = 597,
  [SMALL_STATE(31)] = 616,
  [SMALL_STATE(32)] = 631,
  [SMALL_STATE(33)] = 644,
  [SMALL_STATE(34)] = 661,
  [SMALL_STATE(35)] = 674,
  [SMALL_STATE(36)] = 691,
  [SMALL_STATE(37)] = 704,
  [SMALL_STATE(38)] = 721,
  [SMALL_STATE(39)] = 738,
  [SMALL_STATE(40)] = 751,
  [SMALL_STATE(41)] = 768,
  [SMALL_STATE(42)] = 784,
  [SMALL_STATE(43)] = 796,
  [SMALL_STATE(44)] = 810,
  [SMALL_STATE(45)] = 822,
  [SMALL_STATE(46)] = 836,
  [SMALL_STATE(47)] = 848,
  [SMALL_STATE(48)] = 859,
  [SMALL_STATE(49)] = 870,
  [SMALL_STATE(50)] = 880,
  [SMALL_STATE(51)] = 890,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sep, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sep, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, 0, 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, 0, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [200] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rho(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
