#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym__sep_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_LT_DASH = 4,
  anon_sym_AMP = 5,
  sym_drop = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_LBRACK = 11,
  anon_sym_RBRACK = 12,
  anon_sym_DQUOTE = 13,
  aux_sym_string_token1 = 14,
  sym_escape_sequence = 15,
  sym_number = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_DASH_DASH = 21,
  aux_sym_comment_token1 = 22,
  sym_program = 23,
  sym__sep = 24,
  sym__statement = 25,
  sym_definition = 26,
  sym__expression = 27,
  sym_apply = 28,
  sym__atom = 29,
  sym_quote = 30,
  sym_fn = 31,
  sym_param = 32,
  sym_block = 33,
  sym_array = 34,
  sym_string = 35,
  sym_primitive = 36,
  sym_comment = 37,
  aux_sym_program_repeat1 = 38,
  aux_sym_apply_repeat1 = 39,
  aux_sym_fn_repeat1 = 40,
  aux_sym_block_repeat1 = 41,
  aux_sym_string_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym__sep_token1] = "_sep_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_LT_DASH] = "<-",
  [anon_sym_AMP] = "&",
  [sym_drop] = "drop",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_DASH_DASH] = "--",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_program] = "program",
  [sym__sep] = "_sep",
  [sym__statement] = "_statement",
  [sym_definition] = "definition",
  [sym__expression] = "_expression",
  [sym_apply] = "apply",
  [sym__atom] = "_atom",
  [sym_quote] = "quote",
  [sym_fn] = "fn",
  [sym_param] = "param",
  [sym_block] = "block",
  [sym_array] = "array",
  [sym_string] = "string",
  [sym_primitive] = "primitive",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_apply_repeat1] = "apply_repeat1",
  [aux_sym_fn_repeat1] = "fn_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym__sep_token1] = aux_sym__sep_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LT_DASH] = anon_sym_LT_DASH,
  [anon_sym_AMP] = anon_sym_AMP,
  [sym_drop] = sym_drop,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_program] = sym_program,
  [sym__sep] = sym__sep,
  [sym__statement] = sym__statement,
  [sym_definition] = sym_definition,
  [sym__expression] = sym__expression,
  [sym_apply] = sym_apply,
  [sym__atom] = sym__atom,
  [sym_quote] = sym_quote,
  [sym_fn] = sym_fn,
  [sym_param] = sym_param,
  [sym_block] = sym_block,
  [sym_array] = sym_array,
  [sym_string] = sym_string,
  [sym_primitive] = sym_primitive,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_apply_repeat1] = aux_sym_apply_repeat1,
  [aux_sym_fn_repeat1] = aux_sym_fn_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__sep_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_drop] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__sep] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_apply] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_apply_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fn_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_name = 2,
  field_params = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_name] = "name",
  [field_params] = "params",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_name, 0},
  [2] =
    {field_body, 3},
    {field_params, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '\n', 6,
        '"', 17,
        '&', 9,
        '(', 11,
        ')', 12,
        '*', 27,
        '+', 25,
        '-', 26,
        '.', 10,
        '/', 28,
        ';', 7,
        '<', 2,
        '[', 15,
        '\\', 3,
        ']', 16,
        '{', 13,
        '}', 14,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == '"' ||
          lookahead == '0' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(21);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym__sep_token1);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT_DASH);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_drop);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(20);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 32},
  [53] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym__sep_token1] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LT_DASH] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym_drop] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(50),
    [sym__statement] = STATE(27),
    [sym_definition] = STATE(42),
    [sym__expression] = STATE(42),
    [sym_apply] = STATE(32),
    [sym__atom] = STATE(10),
    [sym_quote] = STATE(19),
    [sym_fn] = STATE(32),
    [sym_array] = STATE(19),
    [sym_string] = STATE(19),
    [sym_primitive] = STATE(19),
    [sym_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_AMP] = ACTIONS(9),
    [sym_drop] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [2] = {
    [sym__sep] = STATE(15),
    [sym__expression] = STATE(39),
    [sym_apply] = STATE(32),
    [sym__atom] = STATE(10),
    [sym_quote] = STATE(19),
    [sym_fn] = STATE(32),
    [sym_array] = STATE(19),
    [sym_string] = STATE(19),
    [sym_primitive] = STATE(19),
    [sym_comment] = STATE(2),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(19),
    [aux_sym__sep_token1] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_AMP] = ACTIONS(9),
    [sym_drop] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [3] = {
    [sym__sep] = STATE(15),
    [sym__expression] = STATE(47),
    [sym_apply] = STATE(32),
    [sym__atom] = STATE(10),
    [sym_quote] = STATE(19),
    [sym_fn] = STATE(32),
    [sym_array] = STATE(19),
    [sym_string] = STATE(19),
    [sym_primitive] = STATE(19),
    [sym_comment] = STATE(3),
    [aux_sym_block_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(29),
    [aux_sym__sep_token1] = ACTIONS(32),
    [anon_sym_SEMI] = ACTIONS(32),
    [anon_sym_AMP] = ACTIONS(35),
    [sym_drop] = ACTIONS(38),
    [anon_sym_LPAREN] = ACTIONS(41),
    [anon_sym_RBRACE] = ACTIONS(44),
    [anon_sym_LBRACK] = ACTIONS(46),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [sym_number] = ACTIONS(29),
    [anon_sym_PLUS] = ACTIONS(52),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(52),
    [anon_sym_SLASH] = ACTIONS(52),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [4] = {
    [sym__sep] = STATE(15),
    [sym__expression] = STATE(40),
    [sym_apply] = STATE(32),
    [sym__atom] = STATE(10),
    [sym_quote] = STATE(19),
    [sym_fn] = STATE(32),
    [sym_array] = STATE(19),
    [sym_string] = STATE(19),
    [sym_primitive] = STATE(19),
    [sym_comment] = STATE(4),
    [aux_sym_block_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(19),
    [aux_sym__sep_token1] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_AMP] = ACTIONS(9),
    [sym_drop] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(58),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [5] = {
    [sym__statement] = STATE(31),
    [sym_definition] = STATE(42),
    [sym__expression] = STATE(42),
    [sym_apply] = STATE(32),
    [sym__atom] = STATE(10),
    [sym_quote] = STATE(19),
    [sym_fn] = STATE(32),
    [sym_array] = STATE(19),
    [sym_string] = STATE(19),
    [sym_primitive] = STATE(19),
    [sym_comment] = STATE(5),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_AMP] = ACTIONS(9),
    [sym_drop] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [6] = {
    [sym__statement] = STATE(45),
    [sym_definition] = STATE(42),
    [sym__expression] = STATE(42),
    [sym_apply] = STATE(32),
    [sym__atom] = STATE(10),
    [sym_quote] = STATE(19),
    [sym_fn] = STATE(32),
    [sym_array] = STATE(19),
    [sym_string] = STATE(19),
    [sym_primitive] = STATE(19),
    [sym_comment] = STATE(6),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(62),
    [sym_identifier] = ACTIONS(64),
    [anon_sym_AMP] = ACTIONS(67),
    [sym_drop] = ACTIONS(70),
    [anon_sym_LPAREN] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(76),
    [anon_sym_DQUOTE] = ACTIONS(79),
    [sym_number] = ACTIONS(82),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_DASH] = ACTIONS(88),
    [anon_sym_STAR] = ACTIONS(85),
    [anon_sym_SLASH] = ACTIONS(85),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [7] = {
    [sym__expression] = STATE(36),
    [sym_apply] = STATE(32),
    [sym__atom] = STATE(10),
    [sym_quote] = STATE(19),
    [sym_fn] = STATE(32),
    [sym_block] = STATE(36),
    [sym_array] = STATE(19),
    [sym_string] = STATE(19),
    [sym_primitive] = STATE(19),
    [sym_comment] = STATE(7),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_AMP] = ACTIONS(9),
    [sym_drop] = ACTIONS(91),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(93),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [8] = {
    [sym__atom] = STATE(18),
    [sym_quote] = STATE(19),
    [sym_array] = STATE(19),
    [sym_string] = STATE(19),
    [sym_primitive] = STATE(19),
    [sym_comment] = STATE(8),
    [aux_sym_apply_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(95),
    [sym_identifier] = ACTIONS(97),
    [aux_sym__sep_token1] = ACTIONS(95),
    [anon_sym_SEMI] = ACTIONS(95),
    [anon_sym_AMP] = ACTIONS(100),
    [anon_sym_RBRACE] = ACTIONS(95),
    [anon_sym_LBRACK] = ACTIONS(103),
    [anon_sym_RBRACK] = ACTIONS(95),
    [anon_sym_DQUOTE] = ACTIONS(106),
    [sym_number] = ACTIONS(97),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_DASH] = ACTIONS(112),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(109),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_AMP,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(8), 1,
      aux_sym_apply_repeat1,
    STATE(9), 1,
      sym_comment,
    STATE(18), 1,
      sym__atom,
    ACTIONS(19), 2,
      sym_number,
      sym_identifier,
    ACTIONS(21), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(115), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(19), 4,
      sym_quote,
      sym_array,
      sym_string,
      sym_primitive,
  [46] = 12,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_AMP,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(9), 1,
      aux_sym_apply_repeat1,
    STATE(10), 1,
      sym_comment,
    STATE(18), 1,
      sym__atom,
    ACTIONS(19), 2,
      sym_number,
      sym_identifier,
    ACTIONS(21), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(19), 4,
      sym_quote,
      sym_array,
      sym_string,
      sym_primitive,
  [92] = 14,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_AMP,
    ACTIONS(11), 1,
      sym_drop,
    ACTIONS(13), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    STATE(10), 1,
      sym__atom,
    STATE(11), 1,
      sym_comment,
    STATE(46), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number,
      sym_identifier,
    STATE(32), 2,
      sym_apply,
      sym_fn,
    ACTIONS(21), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(19), 4,
      sym_quote,
      sym_array,
      sym_string,
      sym_primitive,
  [142] = 12,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_AMP,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(119), 1,
      anon_sym_RBRACK,
    STATE(8), 1,
      aux_sym_apply_repeat1,
    STATE(12), 1,
      sym_comment,
    STATE(18), 1,
      sym__atom,
    ACTIONS(19), 2,
      sym_number,
      sym_identifier,
    ACTIONS(21), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(19), 4,
      sym_quote,
      sym_array,
      sym_string,
      sym_primitive,
  [185] = 12,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_AMP,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(121), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      aux_sym_apply_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(18), 1,
      sym__atom,
    ACTIONS(19), 2,
      sym_number,
      sym_identifier,
    ACTIONS(21), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
    STATE(19), 4,
      sym_quote,
      sym_array,
      sym_string,
      sym_primitive,
  [228] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(125), 1,
      anon_sym_DASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(123), 14,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [254] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(129), 1,
      anon_sym_DASH,
    STATE(15), 1,
      sym_comment,
    ACTIONS(127), 13,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [279] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(133), 1,
      anon_sym_DASH,
    STATE(16), 1,
      sym_comment,
    ACTIONS(131), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [304] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(137), 1,
      anon_sym_DASH,
    STATE(17), 1,
      sym_comment,
    ACTIONS(135), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [329] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(141), 1,
      anon_sym_DASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(139), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [354] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(145), 1,
      anon_sym_DASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(143), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [379] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(149), 1,
      anon_sym_DASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(147), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [404] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(153), 1,
      anon_sym_DASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(151), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [429] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(157), 1,
      anon_sym_DASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(155), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [454] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(161), 1,
      anon_sym_DASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(159), 13,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [479] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(163), 1,
      anon_sym_DASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(44), 13,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [504] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(145), 1,
      anon_sym_DASH,
    ACTIONS(165), 1,
      anon_sym_LT_DASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(143), 11,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_AMP,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [530] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(167), 1,
      anon_sym_DASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(62), 11,
      ts_builtin_sym_end,
      anon_sym_AMP,
      sym_drop,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_number,
      sym_identifier,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
  [553] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym__sep,
    STATE(27), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [570] = 6,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(169), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_comment,
    STATE(33), 1,
      aux_sym_fn_repeat1,
    STATE(49), 1,
      sym_param,
  [589] = 4,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    ACTIONS(178), 1,
      anon_sym_DASH_DASH,
    ACTIONS(175), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
    STATE(29), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [604] = 5,
    ACTIONS(178), 1,
      anon_sym_DASH_DASH,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      aux_sym_string_repeat1,
    STATE(30), 1,
      sym_comment,
    ACTIONS(182), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [621] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym__sep,
    STATE(31), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [638] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [651] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      sym_param,
    STATE(33), 2,
      sym_comment,
      aux_sym_fn_repeat1,
  [668] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(191), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [681] = 5,
    ACTIONS(178), 1,
      anon_sym_DASH_DASH,
    ACTIONS(193), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      aux_sym_string_repeat1,
    STATE(35), 1,
      sym_comment,
    ACTIONS(182), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [698] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(191), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [711] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(195), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [724] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(38), 1,
      sym_comment,
    ACTIONS(197), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [737] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym__sep,
    STATE(39), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [754] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym__sep,
    STATE(40), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [771] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(41), 1,
      sym_comment,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [784] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(42), 1,
      sym_comment,
    ACTIONS(203), 3,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [796] = 3,
    ACTIONS(178), 1,
      anon_sym_DASH_DASH,
    STATE(43), 1,
      sym_comment,
    ACTIONS(205), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      sym_escape_sequence,
  [808] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(169), 1,
      sym_identifier,
    STATE(28), 1,
      aux_sym_fn_repeat1,
    STATE(44), 1,
      sym_comment,
    STATE(49), 1,
      sym_param,
  [824] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(26), 1,
      sym__sep,
    STATE(45), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [838] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(46), 1,
      sym_comment,
    ACTIONS(207), 3,
      ts_builtin_sym_end,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [850] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(24), 1,
      sym__sep,
    STATE(47), 1,
      sym_comment,
    ACTIONS(25), 2,
      aux_sym__sep_token1,
      anon_sym_SEMI,
  [864] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(209), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [875] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(49), 1,
      sym_comment,
    ACTIONS(211), 2,
      anon_sym_RPAREN,
      sym_identifier,
  [886] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      sym_comment,
  [896] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(215), 1,
      sym_identifier,
    STATE(51), 1,
      sym_comment,
  [906] = 3,
    ACTIONS(178), 1,
      anon_sym_DASH_DASH,
    ACTIONS(217), 1,
      aux_sym_comment_token1,
    STATE(52), 1,
      sym_comment,
  [916] = 1,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 46,
  [SMALL_STATE(11)] = 92,
  [SMALL_STATE(12)] = 142,
  [SMALL_STATE(13)] = 185,
  [SMALL_STATE(14)] = 228,
  [SMALL_STATE(15)] = 254,
  [SMALL_STATE(16)] = 279,
  [SMALL_STATE(17)] = 304,
  [SMALL_STATE(18)] = 329,
  [SMALL_STATE(19)] = 354,
  [SMALL_STATE(20)] = 379,
  [SMALL_STATE(21)] = 404,
  [SMALL_STATE(22)] = 429,
  [SMALL_STATE(23)] = 454,
  [SMALL_STATE(24)] = 479,
  [SMALL_STATE(25)] = 504,
  [SMALL_STATE(26)] = 530,
  [SMALL_STATE(27)] = 553,
  [SMALL_STATE(28)] = 570,
  [SMALL_STATE(29)] = 589,
  [SMALL_STATE(30)] = 604,
  [SMALL_STATE(31)] = 621,
  [SMALL_STATE(32)] = 638,
  [SMALL_STATE(33)] = 651,
  [SMALL_STATE(34)] = 668,
  [SMALL_STATE(35)] = 681,
  [SMALL_STATE(36)] = 698,
  [SMALL_STATE(37)] = 711,
  [SMALL_STATE(38)] = 724,
  [SMALL_STATE(39)] = 737,
  [SMALL_STATE(40)] = 754,
  [SMALL_STATE(41)] = 771,
  [SMALL_STATE(42)] = 784,
  [SMALL_STATE(43)] = 796,
  [SMALL_STATE(44)] = 808,
  [SMALL_STATE(45)] = 824,
  [SMALL_STATE(46)] = 838,
  [SMALL_STATE(47)] = 850,
  [SMALL_STATE(48)] = 864,
  [SMALL_STATE(49)] = 875,
  [SMALL_STATE(50)] = 886,
  [SMALL_STATE(51)] = 896,
  [SMALL_STATE(52)] = 906,
  [SMALL_STATE(53)] = 916,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_apply, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__sep, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__sep, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_apply_repeat1, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_apply_repeat1, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 2, 0, 0),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 4, 0, 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, 0, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_repeat1, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rho(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
